[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
bytecode_hash = 'none'
optimizer_runs = 4_294_967_295

[fmt]
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
wrap_comments = true


# See more config options https://gitbhub.com/foundry-rs/foundry/tree/master/config